export const incidentsPanel = '<section class="incident-panel"><div class="panel-head"><h2>Recent incidents</h2><span>HEURISTIC</span></div><ul id="recent-incidents"><li>No supported incidents yet.</li></ul></section>';
export const incidentDialog = '<dialog id="incident-report" aria-labelledby="incident-title"><div class="autopsy-head"><h2 id="incident-title">SPIDERBRAIN INCIDENT REPORT</h2><button id="close-incident" aria-label="Close incident report">×</button></div><div id="incident-body"></div></dialog>';
export const incidentCss = String.raw`
#incident-body .autopsy-table th:first-child,#incident-body .autopsy-table td:first-child{white-space:nowrap;width:110px}
.incident-panel{border:1px solid var(--line);background:var(--panel);border-radius:3px;margin-top:16px}.incident-panel .panel-head{padding:18px 23px 12px}.incident-panel h2{font-size:15px}.incident-panel ul{list-style:none;padding:0 23px 12px;margin:0;max-height:290px;overflow:auto}.incident-panel li{border-top:1px solid var(--line);padding:10px 0;font-size:12px;color:var(--muted)}.incident-panel button{display:block;width:100%;background:none;border:0;padding:0;text-align:left;font:inherit;color:var(--ink);cursor:pointer;line-height:1.7}.incident-panel button:hover{text-decoration:underline}.incident-panel strong{font:11px ui-monospace,monospace;color:#9c6030;margin-right:8px}.incident-panel strong[data-severity="HIGH"]{color:var(--red)}
#incident-report{width:min(94vw,950px);max-height:88vh;border:1px solid var(--line);border-radius:5px;background:var(--panel);color:var(--ink);padding:24px}#incident-report::backdrop{background:#16261f66}#incident-title{font:15px/1.4 system-ui;font-weight:600;letter-spacing:.04em}#incident-body{padding-top:16px;overflow-wrap:anywhere}#incident-body h3{font:23px/1.3 Georgia,serif;margin:0 0 12px}#incident-body h4{font:600 13px system-ui;margin:20px 0 8px}#incident-body p,#incident-body li{font-size:12px;line-height:1.7;color:#536477}#incident-body .report-meta{font:11px/1.8 ui-monospace,monospace}#incident-body ul{padding-left:18px}#incident-body .report-note{font-size:11px;border-top:1px solid var(--line);padding-top:12px}#incident-body a{display:inline-block;border:1px solid var(--line);padding:7px 12px;font-size:11px;color:var(--deep);text-decoration:none}#incident-body .report-related{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}#incident-body .report-related button{font:11px system-ui;background:transparent;border:1px solid var(--line);padding:6px 8px;color:var(--ink);cursor:pointer}@media(max-width:850px){.incident-panel{grid-column:1/-1;margin-top:0}}@media(max-width:600px){#incident-report{padding:16px}.incident-panel{grid-column:auto}}
`;
export const incidentScript = String.raw`
const reportDialog=document.getElementById('incident-report'),reportBody=document.getElementById('incident-body'),incidentList=document.getElementById('recent-incidents');
let incidentItems=[],incidentBusy=false,incidentVersion=-1,activeReportId=null,reportLoad=0;
const writeReport=(tag,text,className)=>{const node=document.createElement(tag);node.textContent=text;if(className)node.className=className;reportBody.append(node);return node;};
const listReport=(title,items)=>{writeReport('h4',title);const list=document.createElement('ul');for(const text of items){const row=document.createElement('li');row.textContent=text;list.append(row);}reportBody.append(list);};
function renderReport(report,sessions){
 const scroll=reportDialog.scrollTop;reportBody.replaceChildren();activeReportId=report.id;
 writeReport('h3',report.route+' · '+report.summary);
 writeReport('p',report.severity+' · '+report.state+' · risk '+report.risk.toFixed(1)+' · confidence '+Math.round(report.confidence*100)+'%','report-meta');
 writeReport('p',report.id+' · '+new Date(report.timestamp).toLocaleString()+' · '+report.sessionId,'report-meta');
const download=document.createElement('a');download.textContent='EXPORT JSON';download.href='/web/incidents/'+encodeURIComponent(report.id)+'/export';download.download='spiderbrain-incident-'+report.id+'-'+new Date(report.timestamp).toISOString().slice(0,10)+'.json';reportBody.append(download);
 writeReport('p','Sessions involved on this route: '+(sessions||[report.sessionId]).join(', '),'report-meta');
 writeReport('p','HTTP behavior: '+report.httpBehavior.retainedRequests+' retained requests · '+report.httpBehavior.routeRequests+' on this route · '+report.httpBehavior.authFailures+' authentication failures · peak '+report.httpBehavior.peakFrequency+' req/s · '+report.httpBehavior.methods.join(', '),'report-meta');
 if(report.relatedCategories.length)writeReport('p','Related detection labels: '+report.relatedCategories.join(', '),'report-meta');
 listReport('Evidence',report.evidence);listReport('Signal contributions',report.signals.map(c=>(names[c.eye]||c.signal)+' +'+c.value.toFixed(1)+' · '+c.reason));
 writeReport('h4','Timeline and classification progression');const wrap=document.createElement('div'),table=document.createElement('table'),head=document.createElement('tr');wrap.className='autopsy-table-wrap';table.className='autopsy-table';
 for(const label of ['Time','HTTP behavior / evidence','Risk / confidence','Classification']){const th=document.createElement('th');th.textContent=label;head.append(th);}table.append(head);
 for(const row of report.timeline){const tr=document.createElement('tr');for(const text of [new Date(row.timestamp).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false,fractionalSecondDigits:3}),row.method+' '+row.route+' · '+row.status+(row.events.length?' · '+row.events.join('; '):''),row.risk.toFixed(1)+' / '+Math.round(row.confidence*100)+'%',row.previousState!==row.state?row.previousState+' → '+row.state:row.state]){const td=document.createElement('td');td.textContent=text;tr.append(td);}table.append(tr);}wrap.append(table);reportBody.append(wrap);
 listReport('Recommended defensive response',report.recommendedResponse);writeReport('p',report.limitation,'report-note');
 reportDialog.scrollTop=scroll;
}
function reportLoading(){reportLoad++;reportBody.replaceChildren();writeReport('p','Loading retained evidence…');if(!reportDialog.open)reportDialog.showModal();return reportLoad;}
async function viewReport(id,sessions){const token=reportLoading();try{const response=await fetch('/web/incidents/'+encodeURIComponent(id));if(!response.ok)throw new Error('Expired');const report=await response.json();if(token!==reportLoad||!reportDialog.open)return;renderReport(report,sessions);}catch{if(token===reportLoad){reportBody.replaceChildren();writeReport('p','Report unavailable or expired.');}}}
async function openRouteReport(route){const token=reportLoading();activeReportId=null;try{const response=await fetch('/web/route-report?route='+encodeURIComponent(route));if(!response.ok)throw new Error('Unavailable');const value=await response.json();if(token!==reportLoad||!reportDialog.open)return;
 if(value.incidents.length){renderReport(value.incidents[0],value.sessions);if(value.incidents.length>1){const group=document.createElement('div');group.className='report-related';for(const item of value.incidents.slice(1,6)){const button=document.createElement('button');button.textContent=item.summary+' · '+item.sessionId.slice(0,11)+'…';button.addEventListener('click',()=>viewReport(item.id,value.sessions));group.append(button);}reportBody.append(group);}}
 else{reportBody.replaceChildren();writeReport('h3',value.route);writeReport('p',value.state+' · risk '+value.risk.toFixed(1)+' · confidence '+Math.round(value.confidence*100)+'%','report-meta');writeReport('p','No corroborated incident in the retained evidence. A route visit alone is insufficient.');writeReport('p','Sessions involved: '+(value.sessions.join(', ')||'none'),'report-meta');listReport('Recent application events',value.recent.map(row=>new Date(row.timestamp).toLocaleTimeString()+' · '+row.vibration.observation.method+' '+row.currentRoute+' · '+row.vibration.observation.status));}}
 catch{if(token===reportLoad){reportBody.replaceChildren();writeReport('p','Route evidence unavailable.');}}}
async function openSessionReport(id){try{const response=await fetch('/web/incidents?session='+encodeURIComponent(id));if(!response.ok)throw new Error('Unavailable');const value=await response.json();if(value.incidents.length){await viewReport(value.incidents[0].id);return;}}catch{}activeSession=id;body.textContent='Loading stored evidence…';if(!dialog.open)dialog.showModal();showSession();}
const originalNodeSelect=field.onSelect;field.onSelect=route=>{originalNodeSelect(route);openRouteReport(route);};
document.getElementById('close-incident').addEventListener('click',()=>reportDialog.close());reportDialog.addEventListener('close',()=>{activeReportId=null;reportLoad++;});
async function refreshIncidents(){if(!latest||incidentBusy||incidentVersion===latest.status.vibrations)return;incidentBusy=true;incidentVersion=latest.status.vibrations;try{const response=await fetch('/web/incidents');if(!response.ok)throw new Error('Unavailable');const value=await response.json();incidentItems=value.incidents;incidentList.replaceChildren();for(const report of incidentItems.slice(0,8)){const li=document.createElement('li'),button=document.createElement('button'),severity=document.createElement('strong');severity.textContent=report.severity;severity.dataset.severity=report.severity;button.append(severity,document.createTextNode(report.route+' · '+Math.round(report.confidence*100)+'%'),document.createElement('br'),document.createTextNode(report.summary+' · VIEW REPORT'));button.addEventListener('click',()=>viewReport(report.id));li.append(button);incidentList.append(li);}if(!incidentItems.length){const li=document.createElement('li');li.textContent='No supported incidents yet.';incidentList.append(li);}if(reportDialog.open&&activeReportId){const current=incidentItems.find(item=>item.id===activeReportId);if(current)renderReport(current);}}catch{incidentList.textContent='Reports unavailable.';}finally{incidentBusy=false;if(latest&&incidentVersion!==latest.status.vibrations)refreshIncidents();}}
stream.addEventListener('web',refreshIncidents);
`;
