export const presentationPanel = `<div class="observation-tools"><span id="observation-note" role="status">Local observation</span><div><button id="presentation" aria-pressed="false">Presentation</button><button id="fullscreen">Fullscreen</button><button id="reset-observation">Reset observation</button></div></div>`;
export const resetDialog = `<dialog id="reset-confirm" aria-labelledby="reset-title"><h2 id="reset-title">Start a new observation?</h2><p>Clear active sessions, route vibrations, temporary risk and current reports. Stored Web Memory, configuration and downloaded reports remain.</p><div class="reset-actions"><button id="cancel-reset" autofocus>Cancel</button><button id="confirm-reset">Reset observation</button></div><p id="reset-error" role="status"></p></dialog>`;
export const polishCss = String.raw`
@media(max-width:420px){.metrics{grid-template-columns:repeat(3,1fr);row-gap:12px}.metrics div:nth-child(3){border-right:0}.intro{flex-direction:column}.sense{min-width:0;border-left:0;border-top:1px solid var(--line);width:100%;padding:12px 0 0;flex-direction:row;flex-wrap:wrap;align-items:center}.sense small{flex-basis:100%}.brand{font-size:11px}.connection{font-size:9px}}
.observation-tools{display:flex;justify-content:space-between;align-items:center;gap:12px;margin:0 0 15px;font:11px system-ui;color:#536477}.observation-tools>div{display:flex;gap:8px;flex-wrap:wrap}.observation-tools button,.reset-actions button,#strong-report{border:1px solid var(--line);background:var(--panel);border-radius:3px;padding:8px 10px;min-height:36px;color:var(--ink);font:11px system-ui;cursor:pointer}.observation-tools button[aria-pressed="true"]{border-color:var(--deep);color:var(--deep)}.presentation .connection{font-size:14px}.presentation .sense strong{font-size:28px}.presentation main{max-width:1680px}.presentation .intro{margin-bottom:30px}#strong-meta{font:11px/1.8 ui-monospace,monospace;overflow-wrap:anywhere;color:#536477}#strong-report[hidden]{display:none}#reset-confirm{width:min(92vw,460px);border:1px solid var(--line);border-radius:5px;background:var(--panel);color:var(--ink);padding:24px}#reset-confirm::backdrop{background:#16261f66}#reset-confirm h2{font:24px Georgia,serif}#reset-confirm p{font:13px/1.7 system-ui;color:#536477}.reset-actions{display:flex;justify-content:flex-end;gap:8px}#confirm-reset{border-color:#b33b31;color:#a5342b}.autopsy-head{position:sticky;top:-24px;background:var(--panel);padding:6px 0;z-index:2}.autopsy-head button{min-width:36px;min-height:36px}.autopsy-table th{color:#243442;background:#fcfcfb}.autopsy-table td{vertical-align:top}.autopsy-table th,.autopsy-table td{line-height:1.65}.autopsy-table-wrap{max-width:100%}#incident-report,#session-autopsy{overscroll-behavior:contain}#incident-body .autopsy-table{min-width:580px}#incident-body .autopsy-table td:nth-child(3){white-space:nowrap}.incident-panel li{padding:11px 0}.incident-panel button{min-height:44px}.incident-panel .incident-label{display:block;color:#536477}.incident-panel .incident-head{display:flex;justify-content:space-between;gap:12px}.incident-panel button:hover,.session-panel button:hover{color:var(--deep)}
@media(max-width:600px){.observation-tools{flex-direction:column;align-items:flex-start}.observation-tools>div{width:100%}.observation-tools button{flex:1;padding:8px 6px;min-height:40px}#incident-report,#session-autopsy{width:94vw;max-height:90dvh;padding:16px}.autopsy-head{top:-16px}.autopsy-head h2{font-size:15px}.presentation .sense strong{font-size:22px}.evidence h3{font-size:20px}#incident-body h3{font-size:20px}}
`;
export const polishScript = String.raw`
const strongMeta=document.createElement('p'),strongReport=document.createElement('button');strongMeta.id='strong-meta';strongReport.id='strong-report';strongReport.textContent='View report';strongReport.hidden=true;el('reason').after(strongMeta,strongReport);
let retainedIncident=null,significantVersion=-1,significantBusy=false;
function showSignificant(){
 el('evidence-title').textContent='Strongest recent vibration';strongMeta.textContent='';strongReport.hidden=true;
 if(latest?.strongest){strongMeta.textContent='Session '+latest.strongest.observation.sessionId;return;}
 if(!retainedIncident)return;
 const report=retainedIncident;el('evidence-title').textContent='Last significant vibration';el('strong-route').textContent=report.route;el('risk').textContent=report.risk.toFixed(1);el('confidence').textContent=Math.round(report.confidence*100)+'%';el('reason').textContent=report.summary;
 strongMeta.textContent=report.severity+' · '+report.state+' · '+new Date(report.timestamp).toLocaleString()+' · session '+report.sessionId;strongReport.hidden=false;
 el('contributions').replaceChildren();for(const signal of report.signals){const li=document.createElement('li'),b=document.createElement('b'),label=document.createElement('span');b.textContent='+'+signal.value.toFixed(1);label.textContent=(names[signal.eye]||signal.signal)+' · '+signal.signal;li.append(b,label);li.title=signal.reason;el('contributions').append(li);}el('decay').textContent='Historical assessment; live energy continues to decay.';
}
async function significant(){if(!latest||significantBusy||significantVersion===latest.status.vibrations){showSignificant();return;}significantBusy=true;significantVersion=latest.status.vibrations;try{const response=await fetch('/web/significant');if(response.ok)retainedIncident=(await response.json()).incident;}catch{}finally{significantBusy=false;showSignificant();if(latest&&significantVersion!==latest.status.vibrations)significant();}}
strongReport.addEventListener('click',()=>{if(retainedIncident){reportLoading();renderReport(retainedIncident);}});
stream.addEventListener('web',()=>{significant();});
el('presentation').addEventListener('click',()=>{const active=document.body.classList.toggle('presentation');el('presentation').setAttribute('aria-pressed',String(active));el('observation-note').textContent=active?'Presentation · live telemetry only':'Local observation';});
el('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{el('observation-note').textContent='Fullscreen unavailable';}});
document.addEventListener('fullscreenchange',()=>{el('fullscreen').textContent=document.fullscreenElement?'Exit fullscreen':'Fullscreen';});
const resetConfirm=el('reset-confirm');el('reset-observation').addEventListener('click',()=>{el('reset-error').textContent='';resetConfirm.showModal();});el('cancel-reset').addEventListener('click',()=>resetConfirm.close());
el('confirm-reset').addEventListener('click',async()=>{el('confirm-reset').disabled=true;try{const token=await(await fetch('/web/control-token')).json();const response=await fetch('/web/reset',{method:'POST',headers:{'Content-Type':'application/json','X-Spiderbrain-Control':token.token},body:'{}'});if(!response.ok)throw new Error('Reset unavailable');retainedIncident=null;activeReportId=null;activeSession=null;reportDialog.close();dialog.close();selected=null;field.selected=null;seenPulses.clear();resetConfirm.close();const snapshot=await(await fetch('/web/snapshot')).json();update(snapshot);incidentVersion=-1;significantVersion=-1;refreshIncidents();significant();el('observation-note').textContent='New observation started';}catch{el('reset-error').textContent='Observation could not reset. Please retry.';}finally{el('confirm-reset').disabled=false;}});
`;
