import { fieldScript } from './web-field.js';
/** Native browser assets. Observed metadata is inserted exclusively with textContent. */
export const page = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SPIDERBRAIN · Live Web</title><link rel="stylesheet" href="/web.css"><script src="/web.js" defer></script></head>
<body><header><a class="brand" href="/web" aria-label="SpiderBrain Live Web"><svg class="mark" viewBox="0 0 64 64" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M26 30 14 20 22 8 M23 34 10 27 3 37 M23 39 10 36 5 49 M26 43 17 46 15 59 M38 30 50 20 42 8 M41 34 54 27 61 37 M41 39 54 36 59 49 M38 43 47 46 49 59 M27 26 24 21 29 14 M37 26 40 21 35 14"/><path d="M32 27 C18 27 21 46 32 51 C43 46 46 27 32 27Z" fill="currentColor"/></g><path d="m26 35 6 6 6-6" fill="none" stroke="#fff" stroke-width="2"/></svg><span>SPIDERBRAIN</span><small>LIVE WEB / V2</small></a><span id="connection" class="connection" role="status">Connecting</span></header>
<main><section class="intro"><div><p class="eyebrow">SYNGANGLION · LOCAL NERVOUS SYSTEM</p><h1>Feel the web.</h1><p class="subtitle">Every route is a thread. Every request is a vibration.</p></div><div class="sense"><span>SPIDER SENSE</span><strong id="state" data-state="DORMANT" aria-live="polite">DORMANT</strong><small>Observing · no enforcement</small></div></section>
<section class="metrics" aria-label="Web activity"><div>THREADS<strong id="threads">0</strong></div><div>CONNECTIONS<strong id="edges">0</strong></div><div>SESSIONS<strong id="session-count">0</strong></div><div>VIBRATIONS<strong id="vibrations">0</strong></div><div>ENERGY<strong id="energy">0.0</strong></div></section>
<div class="workspace"><section class="web-panel"><div class="panel-head"><h2>Observed route web</h2><span id="graph-detail">Waiting for movement</span></div><div class="web-controls"><button id="reset-camera">Reset camera</button><button id="fit-web">Auto-fit</button><button id="pause-motion" aria-pressed="false">Pause motion</button></div><div id="web" class="web-field" role="group" aria-label="Interactive route web. Left drag to orbit, right drag to pan, scroll to zoom. Route inspection is also available by keyboard."></div><p class="web-hint">Drag to orbit · Right-drag to pan · Scroll to zoom</p><div id="empty" class="empty">No routes observed yet.<br><small>Browse the monitored application to begin.</small></div><div class="legend"><span><i class="route-key"></i>Route</span><span><i class="edge-key"></i>Observed transition</span><span><i class="vibration-key"></i>Recent vibration</span><span><i class="structure-key"></i>Silk structure</span><span><i class="canary-key"></i>Canary</span></div><section id="route-inspection" class="route-inspection" hidden aria-live="polite"><div><h3 id="selected-route"></h3><button id="close-inspection" aria-label="Close route inspection">×</button></div><p id="selected-details"></p><p id="selected-canary"></p></section></section>
<aside><section class="evidence"><h2 id="evidence-title">Strongest recent vibration</h2><h3 id="strong-route">No disturbance</h3><div class="scores"><span class="risk-badge">Risk <b id="risk">0.0</b></span><span>Confidence <b id="confidence">0%</b></span></div><p id="reason" class="muted">Waiting for observations.</p><ul id="contributions"></ul><p id="decay" class="muted"></p><small>Confidence is heuristic evidence strength,<br>not an attack probability.</small></section><section class="session-panel"><div class="panel-head"><h2>Active sessions</h2><span>ANONYMOUS</span></div><ul id="sessions"></ul><p id="canary-status" class="canary-status">Canaries disabled</p></section></aside></div>
<footer><span>SPIDERBRAIN is watching.</span><span>Seven Eyes · bounded diffusion · local Web Memory</span></footer></main></body></html>`;

export const css = String.raw`
button:focus-visible,a:focus-visible{outline:2px solid #194b39;outline-offset:3px}aside{min-width:0}.workspace>*,.intro>div{min-width:0}.web-controls button{min-height:32px}.connection{white-space:nowrap}.connection:not(.online){color:#536477}.empty{pointer-events:none}
@media(max-width:420px){.intro{flex-direction:column}.sense{border-left:0;border-top:1px solid var(--line);width:100%;padding:12px 0 0;flex-direction:row;flex-wrap:wrap;align-items:center}.sense small{flex-basis:100%}.metrics{grid-template-columns:repeat(3,1fr);row-gap:12px}.metrics div{min-width:0}.metrics div:nth-child(3){border:0}.connection{font-size:9px}.brand{font-size:11px}}
:root{color-scheme:light;--bg:#fcfcfb;--panel:#fff;--line:#e0e5e8;--ink:#101d25;--muted:#6b7b8c;--green:#23975e;--deep:#194b39;--red:#d74937}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14px system-ui,-apple-system,"Segoe UI",sans-serif}
header{height:70px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;gap:20px;padding:0 max(5vw,calc((100vw - 1360px)/2))}
.brand{display:flex;align-items:center;gap:18px;text-decoration:none;color:var(--ink);font-size:18px;font-weight:650;letter-spacing:.16em}.mark{width:46px;height:46px;flex-shrink:0}.brand small{border-left:1px solid #d2d9dd;padding:6px 0 6px 20px;margin-left:3px;font:10px ui-monospace,monospace;letter-spacing:.08em;color:var(--muted)}
.connection{display:flex;align-items:center;gap:10px;font:11px ui-monospace,monospace;color:var(--muted)}.connection:before{content:'';width:8px;height:8px;border-radius:50%;background:#a2abb2}.connection.online:before{background:var(--green)}.connection.online{color:#42665a}
main{max-width:1500px;margin:auto;padding:30px 5vw 20px}.intro{display:flex;justify-content:space-between;align-items:center;gap:24px;margin-bottom:22px}.eyebrow{font:10px ui-monospace,monospace;letter-spacing:.15em;color:#5a6a78;margin:0 0 12px}h1{font:normal 52px/1.1 Georgia,"Times New Roman",serif;letter-spacing:-.035em;margin:0 0 6px}.subtitle{font-size:15px;color:#5e6976;margin:0;line-height:1.6}
.sense{display:flex;flex-direction:column;gap:9px;border-left:1px solid var(--line);padding:12px 0 4px 30px;min-width:258px}.sense span{color:var(--muted);font:10px ui-monospace,monospace;letter-spacing:.14em}.sense small{color:var(--muted);font-size:12px;letter-spacing:.04em}.sense strong{font:22px ui-monospace,monospace;letter-spacing:.04em;color:var(--deep)}.sense strong[data-state="ALERT"],.sense strong[data-state="SUSPICIOUS"]{color:#a16a23}.sense strong[data-state="HOSTILE"],.sense strong[data-state="TRAPPED"]{color:var(--red)}
.metrics{display:grid;grid-template-columns:repeat(5,1fr);border:1px solid var(--line);border-radius:7px;margin-bottom:22px;padding:10px 0;background:var(--panel)}.metrics div{padding:7px 28px 4px;color:var(--muted);font:10px ui-monospace,monospace;letter-spacing:.14em;border-right:1px solid var(--line)}.metrics div:last-child{border:0}.metrics strong{display:block;color:var(--ink);font:normal 30px/1.2 Georgia,"Times New Roman",serif;margin-top:7px;letter-spacing:0}
.workspace{display:grid;grid-template-columns:minmax(0,1fr) 344px;gap:18px;align-items:start}.web-panel,.evidence,.session-panel{background:var(--panel);border:1px solid var(--line);border-radius:7px}.web-panel{position:relative;overflow:hidden;min-height:510px}.panel-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:18px 22px}.panel-head h2,.evidence h2{font:600 17px/1.3 Georgia,"Times New Roman",serif;margin:0;letter-spacing:-.02em}.panel-head span{font:10px ui-monospace,monospace;color:var(--muted)}
#web{width:100%;height:auto;display:block}#web text{font:13px ui-monospace,monospace;fill:var(--ink);paint-order:stroke;stroke:var(--panel);stroke-width:5px;stroke-linejoin:round}#web .structure{fill:none;stroke:#ccd2d6;stroke-width:.7;stroke-dasharray:2 5}#web .spoke{stroke:#d7dcde;stroke-width:.7}#web .node{cursor:default}#web .node circle{fill:#7baa92;stroke:#fff;stroke-width:2}#web .node .outline{fill:none;stroke:#77a58d;stroke-width:1.7}#web .node.hot circle{fill:var(--deep)}#web .node.hot .outline{fill:none}#web .pulse{fill:none;stroke:var(--green);transform-box:fill-box;transform-origin:center;animation:vibration 1.2s ease-out forwards}#web .edge{stroke:#b4bcbd;fill:none;stroke-opacity:.75}#web .edge.hot{stroke:var(--green);stroke-opacity:.85}#web .hub-label{font-size:11px;letter-spacing:.06em}.empty{position:absolute;left:15%;right:15%;bottom:17%;text-align:center;color:var(--muted);line-height:1.9}.empty small{font-size:12px}
.legend{display:flex;align-items:center;gap:22px;flex-wrap:wrap;padding:15px 24px;color:var(--muted);font-size:10px}.legend span{display:flex;align-items:center;gap:8px}.legend i{display:inline-block}.route-key{width:8px;height:8px;border-radius:50%;background:var(--deep)}.edge-key,.vibration-key,.structure-key{width:27px;border-top:1px solid #929ca1}.vibration-key{border-top:2px solid var(--green)}.structure-key{border-top:2px dotted #afb9c0}
.evidence{padding:18px 23px 20px;margin-bottom:16px}.evidence h3{font:600 25px/1.3 ui-monospace,monospace;margin:18px 0 14px;overflow-wrap:anywhere}.scores{display:flex;flex-wrap:wrap;gap:12px;font:11px ui-monospace,monospace}.scores span{background:#eff1f3;color:#344354;border-radius:5px;padding:7px 11px}.scores .risk-badge{background:#fce8eb;color:#d8394d}.scores b{font-weight:400}.muted{color:#677587;font-size:12px;line-height:1.6}.evidence #reason{margin:15px 0}.evidence small{display:block;color:var(--muted);font-size:11px;line-height:1.65;border-top:1px solid var(--line);padding-top:12px}.evidence ul,.session-panel ul{list-style:none;padding:0;margin:16px 0}.evidence li{display:flex;align-items:baseline;gap:12px;border-top:1px solid #e9edef;padding:8px 0;font-size:12px;line-height:1.5;color:#4a5663}.evidence li b{flex:0 0 38px;font:600 13px ui-monospace,monospace;color:var(--green)}#decay:empty{display:none}.session-panel .panel-head{padding:18px 23px 16px}.session-panel .panel-head span{letter-spacing:.1em}.session-panel ul{margin:0;padding:0 23px 14px;max-height:260px;overflow:auto}.session-panel li{padding:12px 0 3px;border-top:1px solid var(--line);font:12px ui-monospace,monospace;line-height:1.9;color:#536477;overflow-wrap:anywhere}.session-panel li strong{display:block;font-weight:500;color:#243442}
footer{display:flex;justify-content:space-between;gap:15px;color:var(--muted);font-size:11px;margin-top:24px;line-height:1.7}footer span:last-child{font-size:10px}
.silk-ring{fill:none;stroke:#d9dfe0;stroke-width:.7}.silk-ring:nth-child(2n){stroke-dasharray:2 5}#web .node{cursor:pointer}#web .node.canary .outline{stroke:#ac8240;stroke-dasharray:3 2}#web .node.selected .outline,#web .node:focus-visible .outline{stroke:#101d25;stroke-width:2.6}#web .node:focus{outline:none}#web .dense-label{display:none}#web .selected .dense-label,#web .node:focus .dense-label{display:block}#web .strand-pulse{fill:none;stroke:#23975e;stroke-dasharray:4 7;animation:strand-vibration .9s ease-out forwards}#web .honey-pulse{stroke:#ac8240}#web .traveler{pointer-events:none}.route-inspection{margin:0 24px 18px;border-top:1px solid var(--line);padding-top:14px;font-size:12px;color:var(--muted)}.route-inspection>div{display:flex;align-items:center;justify-content:space-between}.route-inspection h3{font:13px ui-monospace,monospace;color:var(--ink);margin:0}.route-inspection p{line-height:1.6;overflow-wrap:anywhere}.route-inspection button{border:0;background:transparent;color:var(--muted);font-size:22px;cursor:pointer}.canary-status{margin:0 23px 18px;font:10px/1.7 ui-monospace,monospace;color:var(--muted)}.canary-key{width:8px;height:8px;border:1px dashed #ac8240;border-radius:50%}.web-field{position:relative;aspect-ratio:1.5;min-height:360px;touch-action:none;overflow:hidden;cursor:grab}.web-field canvas{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}.web-controls{display:flex;justify-content:flex-end;gap:7px;margin:0 20px}.web-controls button{border:1px solid var(--line);border-radius:3px;background:#fff;color:#536459;font:11px system-ui;padding:5px 9px;cursor:pointer}.web-controls button:hover,.web-controls button:focus-visible{border-color:#6e8778;color:#1e3428}.web-hint{font:10px system-ui;color:var(--muted);margin:0 24px 3px}.route-keyboard-list button{position:absolute;left:12px;bottom:10px;width:1px;height:1px;overflow:hidden;clip-path:inset(50%);border:0}.route-keyboard-list button:focus{width:auto;height:auto;clip-path:none;padding:8px 12px;background:#fff;border:1px solid #436e53;color:#192b20;z-index:2}.metrics{border-left:0;border-right:0;border-radius:0;background:transparent}.evidence,.session-panel{border-radius:3px}.sense span,.metrics div,.panel-head span{font-family:system-ui}.evidence h2,.panel-head h2{font-family:system-ui;font-size:15px;font-weight:600}.evidence h3{font-size:23px}.legend{gap:15px}.evidence li{padding:6px 0}.web-panel .panel-head{padding-bottom:12px}@media(max-width:600px){.web-field{aspect-ratio:1;min-height:300px;touch-action:pan-y}.web-hint{display:none}.web-controls{gap:5px;margin:0 12px}.web-controls button{font-size:10px;padding:5px 7px}}@keyframes strand-vibration{from{stroke-dashoffset:24;opacity:1}to{stroke-dashoffset:0;opacity:0}}@keyframes vibration{from{opacity:.7;transform:scale(1)}to{opacity:0;transform:scale(3.4)}}@media(prefers-reduced-motion:reduce){#web .pulse{animation:none;opacity:0}}
@media(max-width:1050px){.workspace{grid-template-columns:minmax(0,1fr) 300px}.evidence{padding:18px}.evidence h3{font-size:21px}.legend{gap:14px}.panel-head span{font-size:9px}}
@media(max-width:850px){.workspace{grid-template-columns:1fr}aside{display:grid;grid-template-columns:1fr 1fr;gap:16px;align-items:start}.evidence{margin:0}.brand small{display:none}.sense{min-width:190px;padding-left:20px}.metrics div{padding:10px 16px}.web-panel{min-height:0}}
@media(max-width:600px){header{height:64px;gap:12px}.brand{font-size:13px;gap:10px;letter-spacing:.12em}.mark{width:36px;height:36px}.connection{font-size:10px;gap:6px}main{padding:24px 5vw}.intro{align-items:flex-start;gap:15px}.sense{min-width:125px;padding:6px 0 4px 15px}.sense strong{font-size:17px}.sense span{font-size:8px}.sense small{font-size:10px;letter-spacing:0}h1{font-size:36px}.eyebrow{font-size:8px;line-height:1.8}.subtitle{font-size:12px}.metrics div{padding:5px 8px;font-size:8px;letter-spacing:0}.metrics strong{font-size:25px}.workspace{gap:16px}aside{grid-template-columns:1fr}.panel-head{padding:16px}.panel-head h2{font-size:15px}.panel-head span{max-width:45%;text-align:right;line-height:1.6}.legend{gap:12px;padding:12px 16px}.empty{font-size:11px}.empty small{font-size:10px}footer{flex-direction:column;gap:6px}}
`;

export const script = fieldScript + String.raw`
'use strict';
const el=id=>document.getElementById(id);
let latest=null,selected=null;
const seenPulses=new Set(),names={velocity:'Velocity Eye',route:'Route Eye',error:'Error Eye',authentication:'Authentication Eye',movement:'Movement Eye',honey:'Honey Eye',payload:'Payload Anomaly Eye'};
const field=new WebField(el('web'),route=>{selected=route;inspectRoute();});
function connection(label,online){el('connection').textContent=label;el('connection').className=online?'connection online':'connection';}
function inspectRoute(){el('route-inspection').hidden=!selected;if(!selected||!latest)return;const node=latest.graph.nodes.find(n=>n.route===selected),canary=(latest.canaries||[]).find(n=>n.route===selected);el('selected-route').textContent=selected;el('selected-details').textContent=node?node.visits+' visits · energy '+node.energy.toFixed(2)+' · neighboring awareness '+node.awareness.toFixed(2)+' · '+node.neighbors.length+' observed neighbors':canary?'Enabled synthetic resource · no observed requests':'Route expired from the bounded graph';el('selected-canary').textContent=canary?'Canary '+canary.id+' · '+canary.type+' · synthetic content only':'';}
function update(data){latest=data;const s=data.status;el('threads').textContent=s.threads;el('edges').textContent=s.connections??'Unavailable';el('session-count').textContent=s.sessions;el('vibrations').textContent=s.vibrations;el('energy').textContent=s.energy.toFixed(1);el('state').textContent=s.spiderSense||'Unavailable';el('state').dataset.state=s.spiderSense||'DORMANT';connection(s.online?'Connected':'Sensor unavailable',s.online);
 el('empty').hidden=data.graph.nodes.length>0||(data.canaries||[]).length>0;el('graph-detail').textContent=data.graph.nodes.length+' / '+data.graph.totalNodes+' threads · '+data.graph.edges.length+' / '+data.graph.totalEdges+' transitions';el('canary-status').textContent=s.canaries?s.canaries+' canaries enabled · '+(s.honeyTouches||0)+' honey interactions':'Canaries disabled';field.update(data);inspectRoute();
 for(const pulse of data.pulses||[]){if(!pulse.id||seenPulses.has(pulse.id))continue;seenPulses.add(pulse.id);if(seenPulses.size>128)seenPulses.delete(seenPulses.values().next().value);field.impulse(pulse);}
 const event=data.strongest;el('contributions').replaceChildren();if(event){const d=event.decision;el('strong-route').textContent=event.observation.route;el('risk').textContent=d.risk.toFixed(1);el('confidence').textContent=Math.round(d.confidence*100)+'%';el('reason').textContent=d.reason;for(const c of d.contributions){const li=document.createElement('li'),b=document.createElement('b'),label=document.createElement('span');b.textContent='+'+c.value.toFixed(1);label.textContent=names[c.eye]?names[c.eye]+' · '+c.signal:c.signal;li.append(b,label);li.title=c.reason;el('contributions').append(li);}el('decay').textContent=(d.adjustments||[]).map(a=>a.value.toFixed(1)+' '+a.signal+' (already applied)').join('; ');}else{el('strong-route').textContent='No recent disturbance';el('risk').textContent='Unavailable';el('confidence').textContent='Unavailable';el('reason').textContent='No recent decision to inspect.';el('decay').textContent='';}
 el('sessions').replaceChildren();for(const session of data.sessions){const li=document.createElement('li'),strong=document.createElement('strong');strong.textContent=session.id.slice(0,11)+'… · '+session.state;li.append(strong,document.createTextNode(session.route+' · energy '+session.energy.toFixed(1)));el('sessions').append(li);}if(!data.sessions.length){const li=document.createElement('li');li.textContent='No active sessions';el('sessions').append(li);}}
el('reset-camera').addEventListener('click',()=>field.reset());el('fit-web').addEventListener('click',()=>field.fit());el('pause-motion').addEventListener('click',()=>{field.pause(!field.paused);el('pause-motion').textContent=field.paused?'Resume motion':'Pause motion';el('pause-motion').setAttribute('aria-pressed',String(field.paused));});el('close-inspection').addEventListener('click',()=>{selected=null;field.selected=null;field.request();inspectRoute();});
const stream=new EventSource('/web/events');stream.addEventListener('web',event=>{try{update(JSON.parse(event.data));}catch{connection('Telemetry unavailable',false);}});stream.onerror=()=>connection('Reconnecting',false);window.addEventListener('pagehide',()=>stream.close());
`;
