/** Small native WebGL field with a canvas fallback. Never modifies security telemetry. */
export const fieldScript = String.raw`
class WebField {
 constructor(container,onSelect){
  this.container=container;this.onSelect=onSelect;this.spokes=32;this.rings=24;this.count=(this.rings+1)*this.spokes;
  this.vertices=new Float32Array(this.count*3);this.base=new Float32Array(this.count);this.screen=new Float32Array(this.count*2);
  this.links=new Uint16Array(this.rings*this.spokes*4);this.mesh=new Float32Array(this.links.length*3);this.edgesBuffer=new Float32Array(250*32*6);
  this.edgeLinks=new Uint16Array(250*32*2);this.edgeLength=0;this.nodes=[];this.routes=new Map();this.selected=null;this.hovered=-1;this.labelBoxes=new Float32Array(128*4);
  this.impulses=Array.from({length:32},()=>({started:-10000,amplitude:0,source:0,from:-1,distances:new Float32Array(this.count),cosine:new Float32Array(this.count),sine:new Float32Array(this.count),waveA:0,waveB:0,age:100,trail:new Uint16Array(64),trailLength:0,honey:false,red:false}));
  this.camera={yaw:-.22,pitch:.9,zoom:1,panX:0,panY:0};this.paused=false;this.frame=0;this.samples=new Float32Array(120);this.sampleIndex=0;this.sampleCount=0;
  this.canvas=document.createElement('canvas');this.canvas.className='web-mesh';this.overlay=document.createElement('canvas');this.overlay.className='web-labels';
  this.keys=document.createElement('div');this.keys.className='route-keyboard-list';container.append(this.canvas,this.overlay,this.keys);this.ctx=this.overlay.getContext('2d');
  this.motion=window.matchMedia('(prefers-reduced-motion: reduce)');this.mobile=window.matchMedia('(max-width:600px)').matches;
  this.gl=this.mobile?null:this.canvas.getContext('webgl',{alpha:true,antialias:true,powerPreference:'low-power',depth:false,stencil:false,preserveDrawingBuffer:true});
  if(this.gl){try{this.setupGL();}catch{this.gl=null;}}
  container.dataset.renderer=this.mobile?'static 2D canvas':this.gl?'native WebGL + canvas labels':'canvas perspective fallback';container.dataset.vertices=String(this.count);container.dataset.maxImpulses='32';
  let link=0;for(let ring=0;ring<=this.rings;ring++)for(let spoke=0;spoke<this.spokes;spoke++){
   const i=ring*this.spokes+spoke,angle=-Math.PI/2+2*Math.PI*spoke/this.spokes,radius=ring/this.rings;
   this.vertices[i*3]=Math.cos(angle)*radius;this.vertices[i*3+1]=Math.sin(angle)*radius;
   if(ring){this.links[link++]=i;this.links[link++]=ring*this.spokes+(spoke+1)%this.spokes;this.links[link++]=i;this.links[link++]=(ring-1)*this.spokes+spoke;}
  }
  this.sprites={green:this.fieldSprite('52,137,90'),red:this.fieldSprite('184,51,49'),honey:this.fieldSprite('162,122,55')};this.core=this.coreSprite();
  this.dash=[3,6];this.noDash=[];this.intervals=new Float32Array(120);this.intervalCount=0;this.lastTime=0;this.wasActive=false;this.boundFrame=time=>this.render(time);this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(container);
  this.visibility=()=>{if(document.hidden)this.stop();else this.request();};document.addEventListener('visibilitychange',this.visibility);this.motion.addEventListener('change',()=>{this.stop();this.request();});
  let pointer=null;container.addEventListener('pointerdown',event=>{if(event.target.closest('button'))return;pointer={x:event.clientX,y:event.clientY,lastX:event.clientX,lastY:event.clientY,button:event.button};container.setPointerCapture(event.pointerId);});
  container.addEventListener('pointermove',event=>{if(pointer){const dx=event.clientX-pointer.lastX,dy=event.clientY-pointer.lastY;pointer.lastX=event.clientX;pointer.lastY=event.clientY;
   if(pointer.button===2){this.camera.panX+=dx*2/this.width;this.camera.panY-=dy*2/this.height;}else if(!this.mobile){this.camera.yaw+=dx*.006;this.camera.pitch=Math.max(.12,Math.min(1.35,this.camera.pitch+dy*.006));}this.request();
  }else{const box=container.getBoundingClientRect(),next=this.hit(event.clientX-box.left,event.clientY-box.top);if(next!==this.hovered){this.hovered=next;container.style.cursor=next>=0?'pointer':'grab';this.request();}}});
  container.addEventListener('pointerup',event=>{if(pointer&&Math.hypot(event.clientX-pointer.x,event.clientY-pointer.y)<5&&pointer.button===0){const box=container.getBoundingClientRect(),hit=this.hit(event.clientX-box.left,event.clientY-box.top);if(hit>=0)this.select(this.nodes[hit].route);}pointer=null;});
  container.addEventListener('pointercancel',()=>{pointer=null;});container.addEventListener('pointerleave',()=>{if(!pointer){this.hovered=-1;this.request();}});
  container.addEventListener('contextmenu',event=>event.preventDefault());container.addEventListener('wheel',event=>{if(this.mobile)return;event.preventDefault();this.camera.zoom=Math.max(.5,Math.min(3.5,this.camera.zoom*Math.exp(-event.deltaY*.001)));this.request();},{passive:false});
  this.canvas.addEventListener('webglcontextlost',event=>{event.preventDefault();this.gl=null;container.dataset.renderer='canvas perspective fallback';this.request();});
  window.addEventListener('pagehide',()=>{this.stop();this.resizeObserver.disconnect();document.removeEventListener('visibilitychange',this.visibility);});
 }
 setupGL(){const gl=this.gl;const shader=(type,source)=>{const item=gl.createShader(type);gl.shaderSource(item,source);gl.compileShader(item);if(!gl.getShaderParameter(item,gl.COMPILE_STATUS))throw new Error('WebGL unavailable');return item;};
  const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec3 p; uniform vec4 rotation; uniform vec2 scale; uniform vec2 pan; void main(){float x=p.x*rotation.x-p.y*rotation.y;float y=p.x*rotation.y+p.y*rotation.x;vec3 q=vec3(x,y*rotation.z-p.z*rotation.w,y*rotation.w+p.z*rotation.z);float d=3.6-q.z;gl_Position=vec4(q.xy*scale+pan*d,0.,d);}'));
  gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'precision mediump float;uniform vec4 color;void main(){gl_FragColor=color;}'));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error('WebGL unavailable');gl.useProgram(program);
  this.program=program;this.positionAttribute=gl.getAttribLocation(program,'p');this.rotation=gl.getUniformLocation(program,'rotation');this.scale=gl.getUniformLocation(program,'scale');this.pan=gl.getUniformLocation(program,'pan');this.color=gl.getUniformLocation(program,'color');
  this.meshBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.meshBuffer);gl.bufferData(gl.ARRAY_BUFFER,this.mesh.byteLength,gl.DYNAMIC_DRAW);this.edgeBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.edgeBuffer);gl.bufferData(gl.ARRAY_BUFFER,this.edgesBuffer.byteLength,gl.DYNAMIC_DRAW);gl.enable(gl.BLEND);gl.blendFuncSeparate(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA,gl.ONE,gl.ONE_MINUS_SRC_ALPHA);
 }
 fieldSprite(rgb){const canvas=document.createElement('canvas');canvas.width=canvas.height=96;const ctx=canvas.getContext('2d'),gradient=ctx.createRadialGradient(48,48,2,48,48,48);gradient.addColorStop(0,'rgba('+rgb+',.12)');gradient.addColorStop(.5,'rgba('+rgb+',.035)');gradient.addColorStop(1,'rgba('+rgb+',0)');ctx.fillStyle=gradient;ctx.fillRect(0,0,96,96);return canvas;}
 coreSprite(){const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const ctx=canvas.getContext('2d'),gradient=ctx.createRadialGradient(45,38,2,64,64,52);gradient.addColorStop(0,'#e6e9e5');gradient.addColorStop(.55,'#aab5ad');gradient.addColorStop(1,'#58665d');ctx.beginPath();ctx.arc(64,64,51,0,Math.PI*2);ctx.fillStyle=gradient;ctx.fill();ctx.save();ctx.clip();ctx.strokeStyle='rgba(35,52,42,.20)';ctx.lineWidth=.6;for(let i=0;i<48;i++){const x=12+i*2.2;ctx.beginPath();ctx.moveTo(x,10);ctx.bezierCurveTo(x+25*Math.sin(i),43,x-19*Math.cos(i),90,x,119);ctx.stroke();}ctx.restore();return canvas;}
 resize(){const box=this.container.getBoundingClientRect();this.width=Math.max(1,box.width);this.height=Math.max(1,box.height);this.mobile=window.matchMedia('(max-width:600px)').matches;this.container.dataset.renderer=this.mobile?'static 2D canvas':this.gl?'native WebGL + canvas labels':'canvas perspective fallback';const ratio=Math.min(2,window.devicePixelRatio||1);this.ratio=ratio;for(const canvas of [this.canvas,this.overlay]){canvas.width=Math.round(this.width*ratio);canvas.height=Math.round(this.height*ratio);}this.fit();this.request();}
 project(){const camera=this.camera,cy=Math.cos(camera.yaw),sy=Math.sin(camera.yaw),pitch=this.mobile?0:camera.pitch,cp=Math.cos(pitch),sp=Math.sin(pitch),size=Math.min(this.width,this.height)*1.9*camera.zoom;
  this.cy=cy;this.sy=sy;this.cp=cp;this.sp=sp;for(let i=0;i<this.count;i++){const x=this.vertices[i*3],y=this.vertices[i*3+1],z=this.vertices[i*3+2],rx=x*cy-y*sy,ry=x*sy+y*cy,py=ry*cp-z*sp,depth=3.6-ry*sp-z*cp;this.screen[i*2]=this.width/2+rx*size/depth+camera.panX*this.width/2;this.screen[i*2+1]=this.height/2-py*size/depth-camera.panY*this.height/2;}
 }
 fit(){if(!this.width||!this.height)return;this.camera.panX=this.camera.panY=0;this.camera.zoom=1;this.project();let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;for(let i=this.rings*this.spokes;i<this.count;i++){const x=this.screen[i*2],y=this.screen[i*2+1];minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);}this.camera.zoom=Math.max(.5,Math.min(3,(this.width-75)/(maxX-minX),(this.height-135)/(maxY-minY)));this.request();}
 reset(){this.camera.yaw=-.22;this.camera.pitch=.9;this.fit();}
 pause(value){this.paused=value;this.stop();this.request();}
 hit(x,y){let nearest=-1,best=20*20;for(let i=0;i<this.nodes.length;i++){const vertex=this.nodes[i].vertex,dx=this.screen[vertex*2]-x,dy=this.screen[vertex*2+1]-y,d=dx*dx+dy*dy;if(d<best){nearest=i;best=d;}}return nearest;}
 select(route){this.selected=route;this.onSelect(route);this.request();}
 update(data){const graph=data.graph,canaries=new Map((data.canaries||[]).map(entry=>[entry.route,entry])),routes=[...new Set([...graph.nodes.map(node=>node.route),...canaries.keys()])].sort().slice(0,128),signature=JSON.stringify([routes,graph.edges.map(edge=>[edge.from,edge.to])]);
  if(signature!==this.signature){this.signature=signature;this.routes.clear();this.nodes=[];this.keys.replaceChildren();const occupied=new Set();
   for(const route of routes){let hash=2166136261;for(const c of route)hash=Math.imul(hash^c.charCodeAt(0),16777619);hash^=hash>>>16;let spoke=(hash>>>0)%this.spokes,ring=20;while(occupied.has(ring+':'+spoke)){spoke=(spoke+1)%this.spokes;if(spoke===(hash>>>0)%this.spokes)ring-=4;}occupied.add(ring+':'+spoke);const node={route,vertex:ring*this.spokes+spoke,ring,spoke,energy:0,awareness:0,visits:0,honey:canaries.has(route),color:'#87a491'};this.nodes.push(node);this.routes.set(route,node);
    const button=document.createElement('button');button.textContent='Inspect '+route;button.addEventListener('click',()=>this.select(route));button.addEventListener('focus',()=>{this.hovered=this.nodes.indexOf(node);this.request();});button.addEventListener('blur',()=>{this.hovered=-1;this.request();});this.keys.append(button);
   }
   for(const node of this.nodes){node.falloff=new Float32Array(this.count);for(let i=0;i<this.count;i++){const dx=this.vertices[i*3]-this.vertices[node.vertex*3],dy=this.vertices[i*3+1]-this.vertices[node.vertex*3+1];node.falloff[i]=Math.exp(-(dx*dx+dy*dy)*24);}}
   this.edgeLength=0;for(const edge of graph.edges.slice(0,250)){const a=this.routes.get(edge.from),b=this.routes.get(edge.to);if(!a||!b)continue;this.addEdge(a,b);}this.edgeData=this.edgesBuffer.subarray(0,this.edgeLength*3);
  }
  this.base.fill(0);for(const node of this.nodes){const observation=graph.nodes.find(entry=>entry.route===node.route);node.energy=observation?.energy||0;node.awareness=observation?.awareness||0;node.visits=observation?.visits||0;node.honey=canaries.has(node.route);node.color=node.energy>=16?'#b64942':node.energy>=8?'#a87a36':node.energy>=3?'#397958':'#8aa394';
   if(node.energy>=1){const height=Math.min(30,node.energy)*.004;for(let i=0;i<this.count;i++)this.base[i]+=height*node.falloff[i];}
  }
  this.totalEnergy=data.status.energy;this.container.dataset.routeNodes=String(this.nodes.length);this.container.dataset.edges=String(Math.min(250,graph.edges.length));this.request();
 }
 addEdge(a,b){let previous=a.vertex,ring=Math.min(a.ring,b.ring);const add=next=>{if(previous!==next&&this.edgeLength+2<=this.edgeLinks.length){this.edgeLinks[this.edgeLength++]=previous;this.edgeLinks[this.edgeLength++]=next;}previous=next;};for(let r=a.ring-1;r>=ring;r--)add(r*this.spokes+a.spoke);let turn=(b.spoke-a.spoke+this.spokes)%this.spokes,direction=1;if(turn>this.spokes/2){turn=this.spokes-turn;direction=-1;}for(let i=1;i<=turn;i++)add(ring*this.spokes+(a.spoke+direction*i+this.spokes)%this.spokes);for(let r=ring+1;r<=b.ring;r++)add(r*this.spokes+b.spoke);}
 impulse(pulse){if(this.paused||this.motion.matches||this.mobile)return;const node=this.routes.get(pulse.route);if(!node)return;let slot=this.impulses[0];for(const item of this.impulses)if(item.started<slot.started)slot=item;slot.started=performance.now();slot.amplitude=Math.min(12,Math.max(0,pulse.energy))*.019;slot.source=node.vertex;slot.from=this.routes.get(pulse.from)?.vertex??-1;slot.honey=!!pulse.honey;slot.red=pulse.energy>=8;
  slot.trailLength=0;const from=this.routes.get(pulse.from);if(from){const ring=Math.min(from.ring,node.ring),add=vertex=>{if(slot.trailLength<64)slot.trail[slot.trailLength++]=vertex;};add(from.vertex);for(let r=from.ring-1;r>=ring;r--)add(r*this.spokes+from.spoke);let turn=(node.spoke-from.spoke+this.spokes)%this.spokes,direction=1;if(turn>this.spokes/2){turn=this.spokes-turn;direction=-1;}for(let i=1;i<=turn;i++)add(ring*this.spokes+(from.spoke+direction*i+this.spokes)%this.spokes);for(let r=ring+1;r<=node.ring;r++)add(r*this.spokes+node.spoke);}
  for(let i=0;i<this.count;i++){const ring=Math.floor(i/this.spokes),spoke=i%this.spokes,turn=Math.abs(spoke-node.spoke),distance=Math.abs(ring-node.ring)+Math.min(turn,this.spokes-turn)*Math.min(ring,node.ring)*.18,delay=distance*.035,weight=Math.exp(2.8*delay)/(1+distance*.4);slot.distances[i]=delay;slot.cosine[i]=weight*Math.cos(13*delay);slot.sine[i]=weight*Math.sin(13*delay);}this.request();
 }
 request(){if(!this.frame&&!document.hidden)this.frame=requestAnimationFrame(this.boundFrame);}
 stop(){if(this.frame)cancelAnimationFrame(this.frame);this.frame=0;}
 drawLines(buffer,data,length,r,g,b,alpha){const gl=this.gl;gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferSubData(gl.ARRAY_BUFFER,0,data);gl.vertexAttribPointer(this.positionAttribute,3,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(this.positionAttribute);gl.uniform4f(this.color,r,g,b,alpha);gl.drawArrays(gl.LINES,0,length);}
 render(time){this.frame=0;if(document.hidden||!this.width)return;const before=performance.now(),moving=!this.paused&&!this.motion.matches&&!this.mobile;let active=false,corePulse=0;
  if(moving)for(const impulse of this.impulses){impulse.age=(time-impulse.started)/1000;const age=impulse.age;if(age<0||age>3.4||!impulse.amplitude)continue;active=true;const amplitude=impulse.amplitude*Math.exp(-2.8*age);impulse.waveA=amplitude*Math.sin(13*age+.35);impulse.waveB=amplitude*Math.cos(13*age+.35);if(impulse.red)corePulse=Math.max(corePulse,3*Math.abs(Math.sin(13*age))*Math.exp(-2.8*age));}
  for(let i=0;i<this.count;i++){let z=this.base[i]-.035*(this.vertices[i*3]*this.vertices[i*3]+this.vertices[i*3+1]*this.vertices[i*3+1]);if(active)for(const impulse of this.impulses){if(impulse.age<0||impulse.age>3.4||!impulse.amplitude||impulse.age<impulse.distances[i])continue;z+=impulse.waveA*impulse.cosine[i]-impulse.waveB*impulse.sine[i];}this.vertices[i*3+2]=Math.max(-.3,Math.min(.4,z));}
  this.project();for(let i=0;i<this.links.length;i++){const vertex=this.links[i];this.mesh[i*3]=this.vertices[vertex*3];this.mesh[i*3+1]=this.vertices[vertex*3+1];this.mesh[i*3+2]=this.vertices[vertex*3+2];}for(let i=0;i<this.edgeLength;i++){const vertex=this.edgeLinks[i];this.edgesBuffer[i*3]=this.vertices[vertex*3];this.edgesBuffer[i*3+1]=this.vertices[vertex*3+1];this.edgesBuffer[i*3+2]=this.vertices[vertex*3+2];}
  const ctx=this.ctx;ctx.setTransform(this.ratio,0,0,this.ratio,0,0);ctx.clearRect(0,0,this.width,this.height);
  if(this.gl&&!this.mobile){const gl=this.gl;gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.useProgram(this.program);gl.uniform4f(this.rotation,this.cy,this.sy,this.cp,this.sp);gl.uniform2f(this.scale,3.8*this.camera.zoom*Math.min(this.width,this.height)/this.width,3.8*this.camera.zoom*Math.min(this.width,this.height)/this.height);gl.uniform2f(this.pan,this.camera.panX,this.camera.panY);this.drawLines(this.meshBuffer,this.mesh,this.links.length,.39,.43,.42,.32);if(this.edgeLength)this.drawLines(this.edgeBuffer,this.edgeData,this.edgeLength,.32,.43,.37,.42);
  }else{if(this.gl)this.gl.clear(this.gl.COLOR_BUFFER_BIT);ctx.strokeStyle='#d2d9d6';ctx.lineWidth=.65;ctx.beginPath();for(let i=0;i<this.links.length;i+=2){const a=this.links[i],b=this.links[i+1],ring=Math.floor(a/this.spokes);if(this.mobile&&(ring===Math.floor(b/this.spokes)?ring%2:a%2))continue;ctx.moveTo(this.screen[a*2],this.screen[a*2+1]);ctx.lineTo(this.screen[b*2],this.screen[b*2+1]);}ctx.stroke();ctx.strokeStyle='#a6b5ab';ctx.beginPath();for(let i=0;i<this.edgeLength;i+=2){const a=this.edgeLinks[i],b=this.edgeLinks[i+1];ctx.moveTo(this.screen[a*2],this.screen[a*2+1]);ctx.lineTo(this.screen[b*2],this.screen[b*2+1]);}ctx.stroke();}
  for(const node of this.nodes)if(node.energy>=3){const radius=Math.min(58,25+Math.sqrt(node.energy)*4),x=this.screen[node.vertex*2],y=this.screen[node.vertex*2+1];ctx.drawImage(node.honey?this.sprites.honey:node.energy>=16?this.sprites.red:this.sprites.green,x-radius,y-radius,radius*2,radius*2);}
  if(moving)for(const impulse of this.impulses){const age=(time-impulse.started)/1000;if(age<0||age>3.4||!impulse.amplitude)continue;const x=this.screen[impulse.source*2],y=this.screen[impulse.source*2+1];ctx.strokeStyle=impulse.honey?'#a77e38':impulse.red?'#b33b37':'#408b61';ctx.globalAlpha=Math.exp(-2.1*age);ctx.lineWidth=1.2;ctx.beginPath();ctx.ellipse(x,y,8+age*28,6+age*18,0,0,Math.PI*2);ctx.stroke();if(impulse.trailLength>1&&age<1){ctx.setLineDash(this.dash);ctx.beginPath();for(let i=0;i<impulse.trailLength;i++){const v=impulse.trail[i];if(i)ctx.lineTo(this.screen[v*2],this.screen[v*2+1]);else ctx.moveTo(this.screen[v*2],this.screen[v*2+1]);}ctx.stroke();ctx.setLineDash(this.noDash);const cursor=age*(impulse.trailLength-1),segment=Math.min(impulse.trailLength-2,Math.floor(cursor)),fraction=cursor-segment,a=impulse.trail[segment],b=impulse.trail[segment+1],ax=this.screen[a*2],ay=this.screen[a*2+1],bx=this.screen[b*2],by=this.screen[b*2+1];ctx.beginPath();ctx.arc(ax+(bx-ax)*fraction,ay+(by-ay)*fraction,2.5,0,Math.PI*2);ctx.fillStyle=ctx.strokeStyle;ctx.fill();}ctx.globalAlpha=1;}
  let labelCount=1;this.labelBoxes[0]=this.screen[0]-58;this.labelBoxes[1]=this.screen[1]-38;this.labelBoxes[2]=this.screen[0]+58;this.labelBoxes[3]=this.screen[1]+58;ctx.textAlign='center';ctx.font=this.mobile?'10px ui-monospace,monospace':'12px ui-monospace,monospace';for(let i=0;i<this.nodes.length;i++){const node=this.nodes[i],x=this.screen[node.vertex*2],y=this.screen[node.vertex*2+1],radius=5+Math.min(5,Math.sqrt(node.energy));ctx.beginPath();ctx.arc(x,y,radius+3,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle=node.honey?'#a37e3d':node.color;ctx.lineWidth=node.route===this.selected||i===this.hovered?2:1;ctx.stroke();ctx.beginPath();ctx.arc(x,y,radius,0,Math.PI*2);ctx.fillStyle=node.color;ctx.fill();if(this.nodes.length<=24||node.route===this.selected||i===this.hovered){const label=node.route.length>38?node.route.slice(0,35)+'…':node.route,half=ctx.measureText(label).width/2+3,lx=Math.max(half+4,Math.min(this.width-half-4,x));let ly=y+radius+17;for(let attempt=0;attempt<16;attempt++){let overlap=false;for(let box=0;box<labelCount;box++){const offset=box*4;if(lx-half<this.labelBoxes[offset+2]&&lx+half>this.labelBoxes[offset]&&ly-11<this.labelBoxes[offset+3]&&ly+3>this.labelBoxes[offset+1]){overlap=true;break;}}if(!overlap)break;ly=attempt<7?y+radius+17+(attempt+1)*14:y-radius-9-(attempt-7)*14;}ly=Math.max(14,Math.min(this.height-12,ly));const offset=labelCount++*4;this.labelBoxes[offset]=lx-half;this.labelBoxes[offset+1]=ly-11;this.labelBoxes[offset+2]=lx+half;this.labelBoxes[offset+3]=ly+3;ctx.lineWidth=4;ctx.strokeStyle='#fff';ctx.strokeText(label,lx,ly);ctx.fillStyle='#1d2a24';ctx.fillText(label,lx,ly);}}
  const coreX=this.screen[0],coreY=this.screen[1],size=56+Math.min(4,(this.totalEnergy||0)/20)+corePulse;ctx.drawImage(this.core,coreX-size/2,coreY-size/2,size,size);ctx.font='11px ui-monospace,monospace';ctx.strokeStyle='#fff';ctx.lineWidth=5;ctx.strokeText('SYNGANGLION',coreX,coreY+size/2+18);ctx.fillStyle='#25372b';ctx.fillText('SYNGANGLION',coreX,coreY+size/2+18);
  if(active&&this.wasActive){this.intervals[this.intervalCount%120]=time-this.lastTime;this.intervalCount++;}this.wasActive=active;this.lastTime=time;
  this.samples[this.sampleIndex]=performance.now()-before;this.sampleIndex=(this.sampleIndex+1)%this.samples.length;this.sampleCount++;if(this.sampleCount%30===0){const sorted=Array.from(this.samples.slice(0,Math.min(this.sampleCount,this.samples.length))).sort((a,b)=>a-b);this.container.dataset.frameP95Ms=sorted[Math.ceil(sorted.length*.95)-1].toFixed(3);this.container.dataset.frames=String(this.sampleCount);if(this.intervalCount){const cadence=Array.from(this.intervals.slice(0,Math.min(120,this.intervalCount))).sort((a,b)=>a-b);this.container.dataset.frameIntervalP95Ms=cadence[Math.ceil(cadence.length*.95)-1].toFixed(3);}}const motion=active?'active':'idle';if(this.container.dataset.motion!==motion)this.container.dataset.motion=motion;if(active)this.request();
 }
}
`;
